import "@/css/globals.css";

import type { Metadata } from "next";
import { Montserrat, Nunito } from "next/font/google";
import { ReactNode } from "react";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["vietnamese"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="vi" suppressHydrationWarning={true}>
      <body className={`${montserrat.variable} ${nunito.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
